// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxN3chFZHD1yrYlT5nc1j3P9hpq6V_2WM',
    appId: '1:468952368714:web:cf8bc9c9319954588c08b3',
    messagingSenderId: '468952368714',
    projectId: 'aikyam1-67825',
    authDomain: 'aikyam1-67825.firebaseapp.com',
    storageBucket: 'aikyam1-67825.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzl6HrC0v49jDJvZzrAnLgBJQx5wlA6B4',
    appId: '1:468952368714:android:c38730e6febe66c18c08b3',
    messagingSenderId: '468952368714',
    projectId: 'aikyam1-67825',
    storageBucket: 'aikyam1-67825.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMy5m7uzkAyIs9KS___Hm_m9gaYo8BVzA',
    appId: '1:468952368714:ios:228b21a353ac4edb8c08b3',
    messagingSenderId: '468952368714',
    projectId: 'aikyam1-67825',
    storageBucket: 'aikyam1-67825.appspot.com',
    iosBundleId: 'com.example.aikyamm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMy5m7uzkAyIs9KS___Hm_m9gaYo8BVzA',
    appId: '1:468952368714:ios:228b21a353ac4edb8c08b3',
    messagingSenderId: '468952368714',
    projectId: 'aikyam1-67825',
    storageBucket: 'aikyam1-67825.appspot.com',
    iosBundleId: 'com.example.aikyamm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxN3chFZHD1yrYlT5nc1j3P9hpq6V_2WM',
    appId: '1:468952368714:web:c72af6bce6e8e2bd8c08b3',
    messagingSenderId: '468952368714',
    projectId: 'aikyam1-67825',
    authDomain: 'aikyam1-67825.firebaseapp.com',
    storageBucket: 'aikyam1-67825.appspot.com',
  );
}
