# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Aikyam

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Trigger manually from GitHub UI
    inputs:
      environment:
        description: 'Deploy to specific environment'
        required: true
        default: 'Production'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Use the required Node.js version

      # Install dependencies, build the project, and run tests
      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # Create a zip file for deployment
      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      # Upload the artifact to the next job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.event.inputs.environment }}  # Use dynamic environment input for flexibility
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Unzip the artifact
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Aikyam'  # Replace with your Azure Web App name
          slot-name: ${{ github.event.inputs.environment }}  # Dynamic slot based on the environment
          package: .  # Deploy the current directory after unzipping
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9B0AC85801234424B24F0BAF6758D13E }}  # Ensure this secret is configured correctly

      # Optionally: Notify on success or failure (via Slack, email, etc.)
